name: Main Branch Style Check

on:
  push:
    branches: [ "main" ]

jobs:
  checkstyle-all:
    name: Check all modules for style
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Run Checkstyle on all modules
        run: mvn checkstyle:check
